name: Test and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'node_modules/**'
      - 'dist/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm ci  # Using `npm ci` to clean install dependencies
          npm i @rollup/rollup-linux-x64-gnu  # Install platform-specific rollup package

      - name: Run Jest tests
        run: npm run test

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm ci  # Using `npm ci` to clean install dependencies
          npm i @rollup/rollup-linux-x64-gnu  # Install platform-specific rollup package

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Lint code
        run: npm run lint

      - name: Lint code
        run: npx eslint "src/**/*.{tsx,ts}"

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
